### ISSUE TITLE
Documentation for Battle and Soccer Arenas

### ISSUE THREAD

**Issue by MTres19** [MTres19/stk-docs#13]
I think this could be part of the Making Tracks tutorial, just add a separate page about navmeshes instead of drivelines and such.

**Comment by Benau** [comment]
From https://supertuxkart.net/New_drivelines#Navmeshes

Navmeshes

Navigation meshes are used by the AI in battle mode. To make a navigation mesh in blender, simpily create a plain mesh above the drivable area of an arena, and than use subdivide or extrude to match the shape of the area. For obstacles avoidance, just make hollow the point or area, takes this example from battleisland:

500px

After finished, set "Type" to "Navmesh" in the supertuxkart properties panel and a navmesh.xml file will be generated when exporting

Notes: Minimap needs all polygons in navigation mesh to have 4 vertices (quads only). Also make sure the normal is correctly calculated, otherwise path-finding for AI won't work.

Here's the missing picture
![r](https://cloud.githubusercontent.com/assets/3252341/11987679/81919656-aa1e-11e5-87bb-c1af6fc61e9d.png)

For soccer is the same, just make sure the goal line lies close the the navmesh, otherwise colorizing it in minimap will fail

**Comment by Benau** [comment]
I want to point out the starting from git version, if navmesh is not made of quads / normal not calculated correctly, you will see explicit warning / error which may lead to fail game-play (assert failed in debug build)
