### ISSUE TITLE
Create new page for kart-object and kart-texture interaction

### ISSUE THREAD

**Issue by MTres19** [MTres19/stk-docs#14]

**Comment by Benau** [comment]
You may want to add documentation for "colorization flag" for karts too.

See latest blender script from media repo

**Comment by MTres19** [comment]
(Sorry for my late reply.)

The problem is that I don't really understand this very well myself. I'll try to explain what I think I know, and you can tell me if I'm correct:

Colorizing randomly changes the color of textures, but you can apply a colorization mask to the texture. Sections in black on the colorization mask won't be colorized, but transparent parts will be colorized.

However, I don't really understand what changing the colorization factor does. I suppose it simply means that if the new color were expressed in HSV, this would control how much more or less vivid the color would be compared to the original. Is this correct?

Also, what do you mean by "colorization flag"? And how can the "hue" parameter of materials be controlled via the Blender GUI add-ons?

**Comment by Benau** [comment]
Colorization factor = the minimum resulting saturation, used to compensate for dim original color

You can take "amanda" kart for example, it has 1.0 factor, because the blue texture is too dim, so when you colorize it, you can barely notice the difference ( which use the original  value).
So set a higher factor will have a deeper resulting color, and 0.0 factor will use the original saturation.

For "hue" parameter, originally I think this function can be used to control the hue of library object too, but @auriamg thinks that we needs to discuss that with @samuncle first.

So for now the hue is controlled by STK only when karts in used in soccer team game

And what do you mean by "colorization flag"? there is no such option

**Comment by MTres19** [comment]
Okay, I understand colorization factor now. I've left colorization as a TODO in the [new materials page](https://supertuxkart.net/Materials) that I've been working on, because it doesn't sound like colorization is quite complete yet.

You mentioned colorization flag in your previous post:

> You may want to add documentation for "colorization flag" for karts too.

<br>
---
<br>

Let me recap what I think I know:

* Currently, colorization is only used for teams in soccer mode, because the "hue" parameter for library objects is not yet developed enough, and we don't want randomly colored purple trees.

* The "hue" parameter currently takes an "H" value from an HSV color and applies it to the texture. (For the screenshot you attached on the original [issue](https://github.com/supertuxkart/stk-code/issues/2338), I assume you set "hue" to something around 85.

* Sections in black on the colorization mask won't be colorized, but transparent parts will be colorized.

Is this correct?

**Comment by Benau** [comment]
"The "hue" parameter currently takes an "H" value from an HSV color and applies it to the texture."

could be

We convert each rgb value in fragment shader to HSV color, and use a custom "hue" parameter to colorize object. And now we use 1.0 / 0.66 (red / blue) hue to change red/blue karts in soccer team game, which is defined in STK source code.

**Comment by Benau** [comment]
You can also mention that if no colorization mask is given, all parts of texture will be colorized

**Comment by MTres19** [comment]
Okay. I think I understand now. Thanks.

If any more progress is made on the hue parameter with regard to library objects, please let me know. Otherwise this is pretty much only relevant for karts right now.

**Comment by Benau** [comment]
Yes sure.

Actually you can ask if @samuncle likes this idea, because it's him who use this feature most, currently  with hard-coded xml you can colorize beach girl in grand paradise island, but @auriamg said the explorer script can't set custom xml properties for library object (which she wanna discuss with him if he thinks it's good enough for him to make track, but sam seems too busy recently)...

**Comment by MTres19** [comment]
Yes. I see two possible types of uses of this:

* Colorizing vegetation, dirt, rock, etc. using slightly different colors to add variety
* Colorizing human-related objects, like karts, clothing, hair color, etc.

For the first one, the best solution I can see is to simply select a median hue for colorization, and then set a certain amount that the shader can deviate from that hue, creating slight variations.

However, for the second one, it might be better to simply have the artist define a color palette for the shader to choose from.

**Comment by MTres19** [comment]
Perhaps I should discuss this with @samuncle though.

**Comment by Benau** [comment]
Currently "colorizing" only works with solid material though

**Comment by MTres19** [comment]
Oh, that's right. But still, there are uses for it, like rocks, and the current palm trees, which don't use alpha test.

**Comment by MTres19** [comment]
Okay, I talked with @samuncle about the options. He approves of my ideas for the two methods of colorizing. I also made two mockups of the Blender interface in the SuperTuxKart Image Properties panel. Red parts already exist, while other parts are things that would be added to support the features.

**Comment by MTres19** [comment]
The first colorization method, "hue deviation":

![colorize-mockup1](https://cloud.githubusercontent.com/assets/18179456/17671422/ecf037f2-62e4-11e6-9699-9cf47b70e7b5.png)

The shader would simply take the take the HSV "H" value for each pixel of the image, and for each object change it a certain amount, up to the change specified by by the "Deviation amount" value. For example, the following boxes each have the same saturation and value, but only the hue is changed. Unless the "Saturation increase/colorization factor" option is set, the saturation does not change. The change in hue is constrained by the deviation amount, making sure that the resulting color is a "nearby" color. For example, for the boxes below, I changed the hue from green toward blue and yellow, but not as far as full blue or red.

![colors](https://cloud.githubusercontent.com/assets/18179456/17671823/f6ced394-62e6-11e6-9f24-17a11c602d88.png)

This would of course obey the colorization mask.

**Comment by MTres19** [comment]
The second colorization method, "color palette":
![colorize-mockup2](https://cloud.githubusercontent.com/assets/18179456/17672104/9463bb5a-62e8-11e6-87ec-628a6f2728b5.png)

For this one, the artist simply gives the shader several RGB colors to pick from to colorize the texture. This might be useful to provide a set of hair colors for the shader to choose from.

This would also obey the colorization mask.

**Comment by MTres19** [comment]
I'm not entirely sure what to do about karts, though I think the hue deviation method would be sufficient. However, the shader would have to ignore the "Deviation amount" property and simply set the hue to whatever hue the soccer team uses.

**Comment by Benau** [comment]
For karts, mainly the color of red/blue is determined by STK, so nothing in blender is required to set

**Comment by Benau** [comment]
Notice: update explorer script (media repo, stk-assets) first, you can open the library object blend of gnu for example

In blender now you should see "Hue settings for colorization" type box, as you can see, you just need to specify float values from > 0.0 to (or equal 1) for hue. The values demonstrated in gnu blend is sorted like rainbow spectrum, ie 1 = red, 0.02 = orange, 0.1 = yellow ... 0.8 = purple.

Also for kart textures you don't need (please don't, if so stk will assert fail currently) to specify those values, because the color of karts will auto change to red/blue if team game

**Comment by MTres19** [comment]
Okay, I've documented it. Thanks for your help with this.
