### ISSUE TITLE
Fix internal links

### ISSUE THREAD

**Issue by konstin** [MTres19/stk-docs#23]
https://supertuxkart.net/Special:LonelyPages and https://supertuxkart.net/Special:WantedPages show that a couple of internal links are broken or missing.

**Comment by MTres19** [comment]
Hmmm... Okay, I'll look into it.

**Comment by MTres19** [comment]
## From the Orphaned Pages page:

A large number of pages are linked to from the skin. They are:

* Donate
* Main Page
* Posters
* Projects

There are a few which I have no idea what to do about:

* The Antarctica pages (are they still up-to-date? Are they needed? Should
some be moved to Talk?)
* Archived News (@auriamg doesn't want to get rid  of this yet, though as I
mentioned the posts are on the blog.)
* Dependencies (I still don't know whether your documentation PR will be
merged.)
* Known Driver Bugs (Would anyone read this anyway? What's your opinion?
Possibly link from FAQ?)
* Privacy (Isn't this related to addons.supertuxkart.net? Isn't it
displayed when you sign up for an account?)

These pages could probably be deleted either because they're just not used
or are probably documented in Doxygen:

* Kart xml
* Add-on status flags

Track Editor Tutorial is actually linked from the Track Editor page, so I'm
not sure why it's showing up on the Orphaned Pages list.

I'm still working on the Maintaining the Wiki page, and I don't want it to
be public yet.

On Tue, Sep 13, 2016 at 3:35 PM, Matthew Trescott <matthewtrescott@gmail.com
> wrote:

> Hmmm... Okay, I'll look into it.
>

**Comment by konstin** [comment]
The important things are done now.
